In this file we will be creating dummy columns from the categorical columns and then we will train an Artificial Neural Network model to predict the Customer Satisfaction Score Finally, we will save the trained model.

First we will load the df_clean dataframe.

In [1]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
# Loading the dataset
df = pd.read_csv('../clean_data/df_clean.csv')

# Checking few rows
df.head()

,channel_name,category,Sub-category,Agent Shift,CSAT Score,responsetime_in_mins,Tenure_Bucket_enc
0,Outcall,Product Queries,Life Insurance,Morning,5,34,0
1,Outcall,Product Queries,Product Specific Information,Morning,5,2,4
2,Inbound,Order Related,Installation/demo,Evening,5,22,0
3,Inbound,Returns,Reverse Pickup Enquiry,Evening,5,20,4
4,Inbound,Cancellation,Not Needed,Morning,5,2,1

We will be encoding the columns of channel_name, category, Sub-category and Agent Shift by creating dummy columns.

In [3]:
# Creating the dummy columns
df_enc = pd.get_dummies(df, columns=['channel_name', 'category', 'Sub-category', 'Agent Shift'], drop_first=False, dtype=int)

# To prevent truncating
pd.set_option('display.max_columns', None)

# Checking few rows of this updated dataframe
df_enc.head()

,CSAT Score,responsetime_in_mins,Tenure_Bucket_enc,channel_name_Email,channel_name_Inbound,channel_name_Outcall,category_App/Website,category_Cancellation,category_Feedback,category_Offers & Cashback,category_Onboarding Related,category_Order Related,category_Others,category_Payments Related,category_Product Queries,category_Refund Related,category_Returns,category_Shopzilla Related,Sub-category_Account updation,Sub-category_Affiliate Offers,Sub-category_App/website Related,Sub-category_Billing Related,Sub-category_COD Refund Details,Sub-category_Call back request,Sub-category_Call disconnected,Sub-category_Card/EMI,Sub-category_Commission related,Sub-category_Customer Requested Modifications,Sub-category_Damaged,Sub-category_Delayed,Sub-category_Exchange / Replacement,Sub-category_Fraudulent User,Sub-category_General Enquiry,Sub-category_Installation/demo,Sub-category_Instant discount,Sub-category_Invoice request,Sub-category_Issues with Shopzilla App,Sub-category_Life Insurance,Sub-category_Missing,Sub-category_Non Order related,Sub-category_Not Needed,Sub-category_Online Payment Issues,Sub-category_Order Verification,Sub-category_Order status enquiry,Sub-category_Other Account Related Issues,Sub-category_Other Cashback,Sub-category_Others,Sub-category_PayLater related,Sub-category_Payment pending,Sub-category_Payment related Queries,Sub-category_Policy Related,Sub-category_Priority delivery,Sub-category_Product Specific Information,Sub-category_Product related Issues,Sub-category_Refund Enquiry,Sub-category_Refund Related Issues,Sub-category_Return cancellation,Sub-category_Return request,Sub-category_Reverse Pickup Enquiry,Sub-category_Self-Help,Sub-category_Seller Cancelled Order,Sub-category_Seller onboarding,Sub-category_Service Center - Service Denial,Sub-category_Service Centres Related,Sub-category_Shopzila Premium Related,Sub-category_Shopzilla Rewards,Sub-category_Signup Issues,Sub-category_Technician Visit,Sub-category_UnProfessional Behaviour,Sub-category_Unable to Login,Sub-category_Unable to track,Sub-category_Wallet related,Sub-category_Warranty related,Sub-category_Wrong,Sub-category_e-Gift Voucher,Agent Shift_Afternoon,Agent Shift_Evening,Agent Shift_Morning,Agent Shift_Night,Agent Shift_Split
0,5,34,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,5,2,4,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,5,22,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,5,20,4,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,5,2,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [4]:
# Checking the name of the columns of df_enc
df_enc.columns.to_list()

['CSAT Score',
 'responsetime_in_mins',
 'Tenure_Bucket_enc',
 'channel_name_Email',
 'channel_name_Inbound',
 'channel_name_Outcall',
 'category_App/Website',
 'category_Cancellation',
 'category_Feedback',
 'category_Offers & Cashback',
 'category_Onboarding Related',
 'category_Order Related',
 'category_Others',
 'category_Payments Related',
 'category_Product Queries',
 'category_Refund Related',
 'category_Returns',
 'category_Shopzilla Related',
 'Sub-category_Account updation',
 'Sub-category_Affiliate Offers',
 'Sub-category_App/website Related',
 'Sub-category_Billing Related',
 'Sub-category_COD Refund Details',
 'Sub-category_Call back request',
 'Sub-category_Call disconnected',
 'Sub-category_Card/EMI',
 'Sub-category_Commission related',
 'Sub-category_Customer Requested Modifications',
 'Sub-category_Damaged',
 'Sub-category_Delayed',
 'Sub-category_Exchange / Replacement',
 'Sub-category_Fraudulent User',
 'Sub-category_General Enquiry',
 'Sub-category_Installation/demo',
 'Sub-category_Instant discount',
 'Sub-category_Invoice request',
 'Sub-category_Issues with Shopzilla App',
 'Sub-category_Life Insurance',
 'Sub-category_Missing',
 'Sub-category_Non Order related',
 'Sub-category_Not Needed',
 'Sub-category_Online Payment Issues',
 'Sub-category_Order Verification',
 'Sub-category_Order status enquiry',
 'Sub-category_Other Account Related Issues',
 'Sub-category_Other Cashback',
 'Sub-category_Others',
 'Sub-category_PayLater related',
 'Sub-category_Payment pending',
 'Sub-category_Payment related Queries',
 'Sub-category_Policy Related',
 'Sub-category_Priority delivery',
 'Sub-category_Product Specific Information',
 'Sub-category_Product related Issues',
 'Sub-category_Refund Enquiry',
 'Sub-category_Refund Related Issues',
 'Sub-category_Return cancellation',
 'Sub-category_Return request',
 'Sub-category_Reverse Pickup Enquiry',
 'Sub-category_Self-Help',
 'Sub-category_Seller Cancelled Order',
 'Sub-category_Seller onboarding',
 'Sub-category_Service Center - Service Denial',
 'Sub-category_Service Centres Related',
 'Sub-category_Shopzila Premium Related',
 'Sub-category_Shopzilla Rewards',
 'Sub-category_Signup Issues',
 'Sub-category_Technician Visit',
 'Sub-category_UnProfessional Behaviour',
 'Sub-category_Unable to Login',
 'Sub-category_Unable to track',
 'Sub-category_Wallet related',
 'Sub-category_Warranty related',
 'Sub-category_Wrong',
 'Sub-category_e-Gift Voucher',
 'Agent Shift_Afternoon',
 'Agent Shift_Evening',
 'Agent Shift_Morning',
 'Agent Shift_Night',
 'Agent Shift_Split']

We will separate the data into training and testing data.

In [5]:
# Defining the features and target variable
x = df_enc.drop('CSAT Score', axis=1)
y = df_enc['CSAT Score']

In [6]:
# Importing the library
from sklearn.model_selection import train_test_split

# Train-Test split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.3, stratify=y)

# Since the target classes are 1-5, we will change them to 0-4
y_train = y_train - 1
y_test = y_test - 1

# Checking the classes
print(y_train.unique())
print(y_test.unique())

# Checking the shape of the splits
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

[4 3 1 0 2]
[4 3 2 0 1]
(57945, 79)
(57945,)
(24834, 79)
(24834,)

We will now scale the column of responsetime_in_mins using StandardScaler.

In [7]:
# Initialising the scaler
scaler = StandardScaler()

# Scaling
x_train[['responsetime_in_mins']] = scaler.fit_transform(x_train[['responsetime_in_mins']])
x_test[['responsetime_in_mins']] = scaler.transform(x_test[['responsetime_in_mins']])

We will now initialise the model and train it.

In [8]:
# Importing the libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix

In [9]:
# Building the neural network
m = Sequential()

m.add(Input(shape=(79,)))                   # Input layer consisting of 79 neurons, equivalent to the number of features

m.add(Dense(256, activation='relu'))        # Hidden layer
m.add(Dropout(0.3))    # Prevents overfiting by randomly disabling 30% of neurons, so that the neurons don't depend on each other and learn independently

m.add(Dense(128, activation='relu'))         # Hidden layer
m.add(Dropout(0.3))    # Dropout layer

m.add(Dense(64, activation='relu'))         # Hidden layer

m.add(Dense(5, activation='softmax'))       # Output layer consisting of 5 neurons, equivalent to the number of classes of the target

# Softmax is used in output layer for probabilty distribution and multi-class classification
# Relu (Rectified Linear Unit) is used in the hidden layers due to it's efficiency and reduced vanishing gradient issues

In [10]:
# Compiling the model
m.compile(optimizer=Adam(learning_rate=0.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [11]:
# Early stopping to avoid overfitting
early_stop = EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)

# Model checkpoint - to save the best model
checkpoint = ModelCheckpoint("best_model.keras", monitor='val_accuracy', save_best_only=True, verbose=1)

In [12]:
# Computing class weights to make the model learn better for minority classes
from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(y_train)
weights = compute_class_weight(classes=classes, class_weight='balanced', y=y_train)
class_weights = dict(enumerate(weights))

In [13]:
# Training the model
history = m.fit(x_train, y_train,
                epochs=50, batch_size=32,
                callbacks=[early_stop, checkpoint],
                validation_split=0.2, class_weight=class_weights)

Epoch 1/50
1446/1449 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2923 - loss: 1.6018
Epoch 1: val_accuracy improved from None to 0.25619, saving model to best_model.keras
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 24s 12ms/step - accuracy: 0.3081 - loss: 1.5930 - val_accuracy: 0.2562 - val_loss: 1.6243
Epoch 2/50
1448/1449 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3647 - loss: 1.5768
Epoch 2: val_accuracy improved from 0.25619 to 0.29442, saving model to best_model.keras
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 19s 12ms/step - accuracy: 0.3598 - loss: 1.5805 - val_accuracy: 0.2944 - val_loss: 1.5471
Epoch 3/50
1447/1449 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3450 - loss: 1.5862
Epoch 3: val_accuracy improved from 0.29442 to 0.54129, saving model to best_model.keras
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 19s 11ms/step - accuracy: 0.3592 - loss: 1.5768 - val_accuracy: 0.5413 - val_loss: 1.5126
Epoch 4/50
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3774 - loss: 1.5699
Epoch 4: val_accuracy did not improve from 0.54129
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.3707 - loss: 1.5751 - val_accuracy: 0.4711 - val_loss: 1.5676
Epoch 5/50
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3906 - loss: 1.5940
Epoch 5: val_accuracy did not improve from 0.54129
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 17s 12ms/step - accuracy: 0.4044 - loss: 1.5721 - val_accuracy: 0.2029 - val_loss: 1.6399
Epoch 6/50
1444/1449 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3891 - loss: 1.5539
Epoch 6: val_accuracy did not improve from 0.54129
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 21s 12ms/step - accuracy: 0.3915 - loss: 1.5671 - val_accuracy: 0.3021 - val_loss: 1.5927
Epoch 7/50
1446/1449 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3706 - loss: 1.5741
Epoch 7: val_accuracy did not improve from 0.54129
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 16s 11ms/step - accuracy: 0.3930 - loss: 1.5663 - val_accuracy: 0.3802 - val_loss: 1.5648
Epoch 8/50
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3712 - loss: 1.5529
Epoch 8: val_accuracy did not improve from 0.54129
1449/1449 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.3698 - loss: 1.5628 - val_accuracy: 0.3905 - val_loss: 1.5876

In [14]:
# Evaluation
test_loss, test_accuracy = m.evaluate(x_test, y_test)
print("Test accuracy:", test_accuracy)
print("Test loss:", test_loss)

777/777 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.5378 - loss: 1.5107
Test accuracy: 0.5377708077430725
Test loss: 1.510685682296753

In [15]:
# Predicting the results
y_pred_prob = m.predict(x_test)
y_pred = y_pred_prob.argmax(axis=1)

777/777 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step

In [16]:
# Performance metrics
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.24      0.38      0.29      3280
           1       0.03      0.01      0.02       372
           2       0.04      0.18      0.07       744
           3       0.12      0.01      0.02      3232
           4       0.75      0.69      0.72     17206

    accuracy                           0.54     24834
   macro avg       0.24      0.25      0.22     24834
weighted avg       0.57      0.54      0.54     24834

[[ 1231    31   536    39  1443]
 [  121     5    69     4   173]
 [  205    13   132    18   376]
 [  653    17   486    34  2042]
 [ 2919    83  2058   193 11953]]

In [ ]:
# Saving the scaler, df_enc dataframe and the list of columns
import os
import joblib

os.makedirs('../artifacts', exist_ok=True)
joblib.dump(scaler, '../artifacts/scaler.pkl')
joblib.dump(x_train.columns.to_list(), '../artifacts/columns.pkl')
df_enc.to_csv('../clean_data/df_enc.csv')